// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: GeoDataRegistry)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/geo_data_registry.go . GeoDataRegistry
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoDataRegistry is a mock of GeoDataRegistry interface.
type MockGeoDataRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockGeoDataRegistryMockRecorder
	isgomock struct{}
}

// MockGeoDataRegistryMockRecorder is the mock recorder for MockGeoDataRegistry.
type MockGeoDataRegistryMockRecorder struct {
	mock *MockGeoDataRegistry
}

// NewMockGeoDataRegistry creates a new mock instance.
func NewMockGeoDataRegistry(ctrl *gomock.Controller) *MockGeoDataRegistry {
	mock := &MockGeoDataRegistry{ctrl: ctrl}
	mock.recorder = &MockGeoDataRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoDataRegistry) EXPECT() *MockGeoDataRegistryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockGeoDataRegistry) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGeoDataRegistryMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGeoDataRegistry)(nil).Delete), name)
}

// FindByName mocks base method.
func (m *MockGeoDataRegistry) FindByName(name string) (domain.GeoDataSource, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(domain.GeoDataSource)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByName indicates an expected call of FindByName.
func (mr *MockGeoDataRegistryMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockGeoDataRegistry)(nil).FindByName), name)
}

// List mocks base method.
func (m *MockGeoDataRegistry) List() ([]domain.GeoDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.GeoDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGeoDataRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGeoDataRegistry)(nil).List))
}

// Save mocks base method.
func (m *MockGeoDataRegistry) Save(source domain.GeoDataSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGeoDataRegistryMockRecorder) Save(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGeoDataRegistry)(nil).Save), source)
}
