// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: GeoDataInspector)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/geo_data_inspector.go . GeoDataInspector
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoDataInspector is a mock of GeoDataInspector interface.
type MockGeoDataInspector struct {
	ctrl     *gomock.Controller
	recorder *MockGeoDataInspectorMockRecorder
	isgomock struct{}
}

// MockGeoDataInspectorMockRecorder is the mock recorder for MockGeoDataInspector.
type MockGeoDataInspectorMockRecorder struct {
	mock *MockGeoDataInspector
}

// NewMockGeoDataInspector creates a new mock instance.
func NewMockGeoDataInspector(ctrl *gomock.Controller) *MockGeoDataInspector {
	mock := &MockGeoDataInspector{ctrl: ctrl}
	mock.recorder = &MockGeoDataInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoDataInspector) EXPECT() *MockGeoDataInspectorMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockGeoDataInspector) Inspect(path string) (domain.InspectedGeoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", path)
	ret0, _ := ret[0].(domain.InspectedGeoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockGeoDataInspectorMockRecorder) Inspect(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockGeoDataInspector)(nil).Inspect), path)
}
