// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: CameraPlanService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/camera_plan_service.go -package mockapplication . CameraPlanService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCameraPlanService is a mock of CameraPlanService interface.
type MockCameraPlanService struct {
	ctrl     *gomock.Controller
	recorder *MockCameraPlanServiceMockRecorder
	isgomock struct{}
}

// MockCameraPlanServiceMockRecorder is the mock recorder for MockCameraPlanService.
type MockCameraPlanServiceMockRecorder struct {
	mock *MockCameraPlanService
}

// NewMockCameraPlanService creates a new mock instance.
func NewMockCameraPlanService(ctrl *gomock.Controller) *MockCameraPlanService {
	mock := &MockCameraPlanService{ctrl: ctrl}
	mock.recorder = &MockCameraPlanServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCameraPlanService) EXPECT() *MockCameraPlanServiceMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockCameraPlanService) Export(plan domain.CameraPlan, path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", plan, path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockCameraPlanServiceMockRecorder) Export(plan, path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockCameraPlanService)(nil).Export), plan, path, overwrite)
}

// Generate mocks base method.
func (m *MockCameraPlanService) Generate(reader io.Reader, parameters domain.PlanParameters) (domain.CameraPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", reader, parameters)
	ret0, _ := ret[0].(domain.CameraPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockCameraPlanServiceMockRecorder) Generate(reader, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockCameraPlanService)(nil).Generate), reader, parameters)
}
