// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: FlightService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/flight_service.go -package mockapplication . FlightService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFlightService is a mock of FlightService interface.
type MockFlightService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightServiceMockRecorder
	isgomock struct{}
}

// MockFlightServiceMockRecorder is the mock recorder for MockFlightService.
type MockFlightServiceMockRecorder struct {
	mock *MockFlightService
}

// NewMockFlightService creates a new mock instance.
func NewMockFlightService(ctrl *gomock.Controller) *MockFlightService {
	mock := &MockFlightService{ctrl: ctrl}
	mock.recorder = &MockFlightServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightService) EXPECT() *MockFlightServiceMockRecorder {
	return m.recorder
}

// Fly mocks base method.
func (m *MockFlightService) Fly(ctx context.Context, reader io.Reader, request domain.FlightRequest, progress func(domain.FlightProgress)) (domain.FlightSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fly", ctx, reader, request, progress)
	ret0, _ := ret[0].(domain.FlightSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fly indicates an expected call of Fly.
func (mr *MockFlightServiceMockRecorder) Fly(ctx, reader, request, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fly", reflect.TypeOf((*MockFlightService)(nil).Fly), ctx, reader, request, progress)
}
