// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: FrameService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/frame_service.go -package mockapplication . FrameService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	context "context"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFrameService is a mock of FrameService interface.
type MockFrameService struct {
	ctrl     *gomock.Controller
	recorder *MockFrameServiceMockRecorder
	isgomock struct{}
}

// MockFrameServiceMockRecorder is the mock recorder for MockFrameService.
type MockFrameServiceMockRecorder struct {
	mock *MockFrameService
}

// NewMockFrameService creates a new mock instance.
func NewMockFrameService(ctrl *gomock.Controller) *MockFrameService {
	mock := &MockFrameService{ctrl: ctrl}
	mock.recorder = &MockFrameServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrameService) EXPECT() *MockFrameServiceMockRecorder {
	return m.recorder
}

// DrawFrame mocks base method.
func (m *MockFrameService) DrawFrame(ctx context.Context, plan domain.CameraPlan, slice domain.GeoSlice, request domain.SingleFrameRequest) (domain.RenderSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawFrame", ctx, plan, slice, request)
	ret0, _ := ret[0].(domain.RenderSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawFrame indicates an expected call of DrawFrame.
func (mr *MockFrameServiceMockRecorder) DrawFrame(ctx, plan, slice, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawFrame", reflect.TypeOf((*MockFrameService)(nil).DrawFrame), ctx, plan, slice, request)
}

// DrawFrames mocks base method.
func (m *MockFrameService) DrawFrames(ctx context.Context, plan domain.CameraPlan, slice domain.GeoSlice, request domain.FrameSetRequest, progress func(domain.RenderProgress)) (domain.RenderSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrawFrames", ctx, plan, slice, request, progress)
	ret0, _ := ret[0].(domain.RenderSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrawFrames indicates an expected call of DrawFrames.
func (mr *MockFrameServiceMockRecorder) DrawFrames(ctx, plan, slice, request, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawFrames", reflect.TypeOf((*MockFrameService)(nil).DrawFrames), ctx, plan, slice, request, progress)
}
