// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: GeoSliceService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/geo_slice_service.go -package mockapplication . GeoSliceService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoSliceService is a mock of GeoSliceService interface.
type MockGeoSliceService struct {
	ctrl     *gomock.Controller
	recorder *MockGeoSliceServiceMockRecorder
	isgomock struct{}
}

// MockGeoSliceServiceMockRecorder is the mock recorder for MockGeoSliceService.
type MockGeoSliceServiceMockRecorder struct {
	mock *MockGeoSliceService
}

// NewMockGeoSliceService creates a new mock instance.
func NewMockGeoSliceService(ctrl *gomock.Controller) *MockGeoSliceService {
	mock := &MockGeoSliceService{ctrl: ctrl}
	mock.recorder = &MockGeoSliceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoSliceService) EXPECT() *MockGeoSliceServiceMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockGeoSliceService) Export(slice domain.GeoSlice, path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", slice, path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockGeoSliceServiceMockRecorder) Export(slice, path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockGeoSliceService)(nil).Export), slice, path, overwrite)
}

// Generate mocks base method.
func (m *MockGeoSliceService) Generate(plan domain.CameraPlan, selection domain.SourceSelection) (domain.GeoSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", plan, selection)
	ret0, _ := ret[0].(domain.GeoSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGeoSliceServiceMockRecorder) Generate(plan, selection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGeoSliceService)(nil).Generate), plan, selection)
}

// Load mocks base method.
func (m *MockGeoSliceService) Load(path string) (domain.GeoSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(domain.GeoSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockGeoSliceServiceMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockGeoSliceService)(nil).Load), path)
}
