// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: InspectTrackService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/inspect_track_service.go -package mockapplication . InspectTrackService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInspectTrackService is a mock of InspectTrackService interface.
type MockInspectTrackService struct {
	ctrl     *gomock.Controller
	recorder *MockInspectTrackServiceMockRecorder
	isgomock struct{}
}

// MockInspectTrackServiceMockRecorder is the mock recorder for MockInspectTrackService.
type MockInspectTrackServiceMockRecorder struct {
	mock *MockInspectTrackService
}

// NewMockInspectTrackService creates a new mock instance.
func NewMockInspectTrackService(ctrl *gomock.Controller) *MockInspectTrackService {
	mock := &MockInspectTrackService{ctrl: ctrl}
	mock.recorder = &MockInspectTrackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInspectTrackService) EXPECT() *MockInspectTrackServiceMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockInspectTrackService) Inspect(reader io.Reader, simplificationLevel, smoothingLevel domain.Level) (domain.TrackSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", reader, simplificationLevel, smoothingLevel)
	ret0, _ := ret[0].(domain.TrackSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockInspectTrackServiceMockRecorder) Inspect(reader, simplificationLevel, smoothingLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockInspectTrackService)(nil).Inspect), reader, simplificationLevel, smoothingLevel)
}
