// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: TrackService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/track_service.go -package mockapplication . TrackService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTrackService is a mock of TrackService interface.
type MockTrackService struct {
	ctrl     *gomock.Controller
	recorder *MockTrackServiceMockRecorder
	isgomock struct{}
}

// MockTrackServiceMockRecorder is the mock recorder for MockTrackService.
type MockTrackServiceMockRecorder struct {
	mock *MockTrackService
}

// NewMockTrackService creates a new mock instance.
func NewMockTrackService(ctrl *gomock.Controller) *MockTrackService {
	mock := &MockTrackService{ctrl: ctrl}
	mock.recorder = &MockTrackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackService) EXPECT() *MockTrackServiceMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockTrackService) Clean(reader io.Reader) (domain.CleanedTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", reader)
	ret0, _ := ret[0].(domain.CleanedTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockTrackServiceMockRecorder) Clean(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockTrackService)(nil).Clean), reader)
}

// Inspect mocks base method.
func (m *MockTrackService) Inspect(reader io.Reader, simplificationLevel, smoothingLevel domain.Level) (domain.TrackSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", reader, simplificationLevel, smoothingLevel)
	ret0, _ := ret[0].(domain.TrackSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockTrackServiceMockRecorder) Inspect(reader, simplificationLevel, smoothingLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockTrackService)(nil).Inspect), reader, simplificationLevel, smoothingLevel)
}

// Treat mocks base method.
func (m *MockTrackService) Treat(reader io.Reader, simplificationLevel, smoothingLevel domain.Level) (domain.TreatedTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Treat", reader, simplificationLevel, smoothingLevel)
	ret0, _ := ret[0].(domain.TreatedTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Treat indicates an expected call of Treat.
func (mr *MockTrackServiceMockRecorder) Treat(reader, simplificationLevel, smoothingLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Treat", reflect.TypeOf((*MockTrackService)(nil).Treat), reader, simplificationLevel, smoothingLevel)
}
