// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: VideoService)
//
// Generated by this command:
//
//	mockgen -destination mockapplication/video_service.go -package mockapplication . VideoService
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	context "context"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoService is a mock of VideoService interface.
type MockVideoService struct {
	ctrl     *gomock.Controller
	recorder *MockVideoServiceMockRecorder
	isgomock struct{}
}

// MockVideoServiceMockRecorder is the mock recorder for MockVideoService.
type MockVideoServiceMockRecorder struct {
	mock *MockVideoService
}

// NewMockVideoService creates a new mock instance.
func NewMockVideoService(ctrl *gomock.Controller) *MockVideoService {
	mock := &MockVideoService{ctrl: ctrl}
	mock.recorder = &MockVideoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoService) EXPECT() *MockVideoServiceMockRecorder {
	return m.recorder
}

// Assemble mocks base method.
func (m *MockVideoService) Assemble(ctx context.Context, plan domain.CameraPlan, request domain.VideoRequest, progress func(domain.VideoProgress)) (domain.VideoSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assemble", ctx, plan, request, progress)
	ret0, _ := ret[0].(domain.VideoSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assemble indicates an expected call of Assemble.
func (mr *MockVideoServiceMockRecorder) Assemble(ctx, plan, request, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assemble", reflect.TypeOf((*MockVideoService)(nil).Assemble), ctx, plan, request, progress)
}

// CheckDestination mocks base method.
func (m *MockVideoService) CheckDestination(output string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDestination", output, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDestination indicates an expected call of CheckDestination.
func (mr *MockVideoServiceMockRecorder) CheckDestination(output, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDestination", reflect.TypeOf((*MockVideoService)(nil).CheckDestination), output, overwrite)
}

// CheckEncoder mocks base method.
func (m *MockVideoService) CheckEncoder(ctx context.Context) (domain.EncoderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEncoder", ctx)
	ret0, _ := ret[0].(domain.EncoderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEncoder indicates an expected call of CheckEncoder.
func (mr *MockVideoServiceMockRecorder) CheckEncoder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEncoder", reflect.TypeOf((*MockVideoService)(nil).CheckEncoder), ctx)
}
