// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: CheckCoverageService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/check_coverage_service.go . CheckCoverageService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/waliqueiroz/sobrevoo/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckCoverageService is a mock of CheckCoverageService interface.
type MockCheckCoverageService struct {
	ctrl     *gomock.Controller
	recorder *MockCheckCoverageServiceMockRecorder
	isgomock struct{}
}

// MockCheckCoverageServiceMockRecorder is the mock recorder for MockCheckCoverageService.
type MockCheckCoverageServiceMockRecorder struct {
	mock *MockCheckCoverageService
}

// NewMockCheckCoverageService creates a new mock instance.
func NewMockCheckCoverageService(ctrl *gomock.Controller) *MockCheckCoverageService {
	mock := &MockCheckCoverageService{ctrl: ctrl}
	mock.recorder = &MockCheckCoverageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckCoverageService) EXPECT() *MockCheckCoverageServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCheckCoverageService) Execute(input application.CheckCoverageInput) (application.CheckCoverageOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(application.CheckCoverageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCheckCoverageServiceMockRecorder) Execute(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCheckCoverageService)(nil).Execute), input)
}
