// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: GeoDataService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/geo_data_service.go . GeoDataService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoDataService is a mock of GeoDataService interface.
type MockGeoDataService struct {
	ctrl     *gomock.Controller
	recorder *MockGeoDataServiceMockRecorder
	isgomock struct{}
}

// MockGeoDataServiceMockRecorder is the mock recorder for MockGeoDataService.
type MockGeoDataServiceMockRecorder struct {
	mock *MockGeoDataService
}

// NewMockGeoDataService creates a new mock instance.
func NewMockGeoDataService(ctrl *gomock.Controller) *MockGeoDataService {
	mock := &MockGeoDataService{ctrl: ctrl}
	mock.recorder = &MockGeoDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoDataService) EXPECT() *MockGeoDataServiceMockRecorder {
	return m.recorder
}

// CheckCoverage mocks base method.
func (m *MockGeoDataService) CheckCoverage(reader io.Reader) (domain.CoverageReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCoverage", reader)
	ret0, _ := ret[0].(domain.CoverageReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCoverage indicates an expected call of CheckCoverage.
func (mr *MockGeoDataServiceMockRecorder) CheckCoverage(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCoverage", reflect.TypeOf((*MockGeoDataService)(nil).CheckCoverage), reader)
}

// List mocks base method.
func (m *MockGeoDataService) List() ([]domain.GeoDataSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.GeoDataSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGeoDataServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGeoDataService)(nil).List))
}

// Register mocks base method.
func (m *MockGeoDataService) Register(name, path string) (domain.GeoDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", name, path)
	ret0, _ := ret[0].(domain.GeoDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockGeoDataServiceMockRecorder) Register(name, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockGeoDataService)(nil).Register), name, path)
}

// Remove mocks base method.
func (m *MockGeoDataService) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockGeoDataServiceMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockGeoDataService)(nil).Remove), name)
}
