// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: InspectTrackService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/inspect_track_service.go . InspectTrackService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/waliqueiroz/sobrevoo/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockInspectTrackService is a mock of InspectTrackService interface.
type MockInspectTrackService struct {
	ctrl     *gomock.Controller
	recorder *MockInspectTrackServiceMockRecorder
	isgomock struct{}
}

// MockInspectTrackServiceMockRecorder is the mock recorder for MockInspectTrackService.
type MockInspectTrackServiceMockRecorder struct {
	mock *MockInspectTrackService
}

// NewMockInspectTrackService creates a new mock instance.
func NewMockInspectTrackService(ctrl *gomock.Controller) *MockInspectTrackService {
	mock := &MockInspectTrackService{ctrl: ctrl}
	mock.recorder = &MockInspectTrackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInspectTrackService) EXPECT() *MockInspectTrackServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockInspectTrackService) Execute(input application.InspectTrackInput) (application.InspectTrackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(application.InspectTrackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockInspectTrackServiceMockRecorder) Execute(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockInspectTrackService)(nil).Execute), input)
}
