// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: ListGeoDataService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/list_geo_data_service.go . ListGeoDataService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/waliqueiroz/sobrevoo/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockListGeoDataService is a mock of ListGeoDataService interface.
type MockListGeoDataService struct {
	ctrl     *gomock.Controller
	recorder *MockListGeoDataServiceMockRecorder
	isgomock struct{}
}

// MockListGeoDataServiceMockRecorder is the mock recorder for MockListGeoDataService.
type MockListGeoDataServiceMockRecorder struct {
	mock *MockListGeoDataService
}

// NewMockListGeoDataService creates a new mock instance.
func NewMockListGeoDataService(ctrl *gomock.Controller) *MockListGeoDataService {
	mock := &MockListGeoDataService{ctrl: ctrl}
	mock.recorder = &MockListGeoDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListGeoDataService) EXPECT() *MockListGeoDataServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListGeoDataService) Execute() (application.ListGeoDataOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(application.ListGeoDataOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListGeoDataServiceMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListGeoDataService)(nil).Execute))
}
