// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: RegisterGeoDataService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/register_geo_data_service.go . RegisterGeoDataService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/waliqueiroz/sobrevoo/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockRegisterGeoDataService is a mock of RegisterGeoDataService interface.
type MockRegisterGeoDataService struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterGeoDataServiceMockRecorder
	isgomock struct{}
}

// MockRegisterGeoDataServiceMockRecorder is the mock recorder for MockRegisterGeoDataService.
type MockRegisterGeoDataServiceMockRecorder struct {
	mock *MockRegisterGeoDataService
}

// NewMockRegisterGeoDataService creates a new mock instance.
func NewMockRegisterGeoDataService(ctrl *gomock.Controller) *MockRegisterGeoDataService {
	mock := &MockRegisterGeoDataService{ctrl: ctrl}
	mock.recorder = &MockRegisterGeoDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterGeoDataService) EXPECT() *MockRegisterGeoDataServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterGeoDataService) Execute(input application.RegisterGeoDataInput) (application.RegisterGeoDataOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(application.RegisterGeoDataOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterGeoDataServiceMockRecorder) Execute(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterGeoDataService)(nil).Execute), input)
}
