// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/application (interfaces: RemoveGeoDataService)
//
// Generated by this command:
//
//	mockgen -destination mock_application/remove_geo_data_service.go . RemoveGeoDataService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/waliqueiroz/sobrevoo/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockRemoveGeoDataService is a mock of RemoveGeoDataService interface.
type MockRemoveGeoDataService struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveGeoDataServiceMockRecorder
	isgomock struct{}
}

// MockRemoveGeoDataServiceMockRecorder is the mock recorder for MockRemoveGeoDataService.
type MockRemoveGeoDataServiceMockRecorder struct {
	mock *MockRemoveGeoDataService
}

// NewMockRemoveGeoDataService creates a new mock instance.
func NewMockRemoveGeoDataService(ctrl *gomock.Controller) *MockRemoveGeoDataService {
	mock := &MockRemoveGeoDataService{ctrl: ctrl}
	mock.recorder = &MockRemoveGeoDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveGeoDataService) EXPECT() *MockRemoveGeoDataServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRemoveGeoDataService) Execute(input application.RemoveGeoDataInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRemoveGeoDataServiceMockRecorder) Execute(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRemoveGeoDataService)(nil).Execute), input)
}
