// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: BaseMapReader)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/base_map_reader.go -package mockdomain . BaseMapReader
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBaseMapReader is a mock of BaseMapReader interface.
type MockBaseMapReader struct {
	ctrl     *gomock.Controller
	recorder *MockBaseMapReaderMockRecorder
	isgomock struct{}
}

// MockBaseMapReaderMockRecorder is the mock recorder for MockBaseMapReader.
type MockBaseMapReaderMockRecorder struct {
	mock *MockBaseMapReader
}

// NewMockBaseMapReader creates a new mock instance.
func NewMockBaseMapReader(ctrl *gomock.Controller) *MockBaseMapReader {
	mock := &MockBaseMapReader{ctrl: ctrl}
	mock.recorder = &MockBaseMapReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseMapReader) EXPECT() *MockBaseMapReaderMockRecorder {
	return m.recorder
}

// Levels mocks base method.
func (m *MockBaseMapReader) Levels(path string) (domain.LevelRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Levels", path)
	ret0, _ := ret[0].(domain.LevelRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Levels indicates an expected call of Levels.
func (mr *MockBaseMapReaderMockRecorder) Levels(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Levels", reflect.TypeOf((*MockBaseMapReader)(nil).Levels), path)
}

// ReadTiles mocks base method.
func (m *MockBaseMapReader) ReadTiles(path string, level int, ids []domain.TileID) (domain.TileRead, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTiles", path, level, ids)
	ret0, _ := ret[0].(domain.TileRead)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTiles indicates an expected call of ReadTiles.
func (mr *MockBaseMapReaderMockRecorder) ReadTiles(path, level, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTiles", reflect.TypeOf((*MockBaseMapReader)(nil).ReadTiles), path, level, ids)
}
