// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: CameraPlanExporter)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/camera_plan_exporter.go -package mockdomain . CameraPlanExporter
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCameraPlanExporter is a mock of CameraPlanExporter interface.
type MockCameraPlanExporter struct {
	ctrl     *gomock.Controller
	recorder *MockCameraPlanExporterMockRecorder
	isgomock struct{}
}

// MockCameraPlanExporterMockRecorder is the mock recorder for MockCameraPlanExporter.
type MockCameraPlanExporterMockRecorder struct {
	mock *MockCameraPlanExporter
}

// NewMockCameraPlanExporter creates a new mock instance.
func NewMockCameraPlanExporter(ctrl *gomock.Controller) *MockCameraPlanExporter {
	mock := &MockCameraPlanExporter{ctrl: ctrl}
	mock.recorder = &MockCameraPlanExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCameraPlanExporter) EXPECT() *MockCameraPlanExporterMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockCameraPlanExporter) Export(plan domain.CameraPlan, path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", plan, path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockCameraPlanExporterMockRecorder) Export(plan, path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockCameraPlanExporter)(nil).Export), plan, path, overwrite)
}
