// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: CameraPlanReader)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/camera_plan_reader.go -package mockdomain . CameraPlanReader
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCameraPlanReader is a mock of CameraPlanReader interface.
type MockCameraPlanReader struct {
	ctrl     *gomock.Controller
	recorder *MockCameraPlanReaderMockRecorder
	isgomock struct{}
}

// MockCameraPlanReaderMockRecorder is the mock recorder for MockCameraPlanReader.
type MockCameraPlanReaderMockRecorder struct {
	mock *MockCameraPlanReader
}

// NewMockCameraPlanReader creates a new mock instance.
func NewMockCameraPlanReader(ctrl *gomock.Controller) *MockCameraPlanReader {
	mock := &MockCameraPlanReader{ctrl: ctrl}
	mock.recorder = &MockCameraPlanReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCameraPlanReader) EXPECT() *MockCameraPlanReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockCameraPlanReader) Read(path string) (domain.CameraPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(domain.CameraPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockCameraPlanReaderMockRecorder) Read(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCameraPlanReader)(nil).Read), path)
}
