// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: ElevationReader)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/elevation_reader.go -package mockdomain . ElevationReader
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockElevationReader is a mock of ElevationReader interface.
type MockElevationReader struct {
	ctrl     *gomock.Controller
	recorder *MockElevationReaderMockRecorder
	isgomock struct{}
}

// MockElevationReaderMockRecorder is the mock recorder for MockElevationReader.
type MockElevationReaderMockRecorder struct {
	mock *MockElevationReader
}

// NewMockElevationReader creates a new mock instance.
func NewMockElevationReader(ctrl *gomock.Controller) *MockElevationReader {
	mock := &MockElevationReader{ctrl: ctrl}
	mock.recorder = &MockElevationReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElevationReader) EXPECT() *MockElevationReaderMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockElevationReader) Describe(path string) (domain.ElevationGridInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", path)
	ret0, _ := ret[0].(domain.ElevationGridInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockElevationReaderMockRecorder) Describe(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockElevationReader)(nil).Describe), path)
}

// ReadWindow mocks base method.
func (m *MockElevationReader) ReadWindow(path string, window domain.GridWindow) (domain.ElevationWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadWindow", path, window)
	ret0, _ := ret[0].(domain.ElevationWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadWindow indicates an expected call of ReadWindow.
func (mr *MockElevationReaderMockRecorder) ReadWindow(path, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadWindow", reflect.TypeOf((*MockElevationReader)(nil).ReadWindow), path, window)
}
