// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: FileChecker)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/file_checker.go -package mockdomain . FileChecker
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileChecker is a mock of FileChecker interface.
type MockFileChecker struct {
	ctrl     *gomock.Controller
	recorder *MockFileCheckerMockRecorder
	isgomock struct{}
}

// MockFileCheckerMockRecorder is the mock recorder for MockFileChecker.
type MockFileCheckerMockRecorder struct {
	mock *MockFileChecker
}

// NewMockFileChecker creates a new mock instance.
func NewMockFileChecker(ctrl *gomock.Controller) *MockFileChecker {
	mock := &MockFileChecker{ctrl: ctrl}
	mock.recorder = &MockFileCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileChecker) EXPECT() *MockFileCheckerMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockFileChecker) Exists(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockFileCheckerMockRecorder) Exists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFileChecker)(nil).Exists), path)
}
