// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: FrameExporter)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/frame_exporter.go -package mockdomain . FrameExporter
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFrameExporter is a mock of FrameExporter interface.
type MockFrameExporter struct {
	ctrl     *gomock.Controller
	recorder *MockFrameExporterMockRecorder
	isgomock struct{}
}

// MockFrameExporterMockRecorder is the mock recorder for MockFrameExporter.
type MockFrameExporterMockRecorder struct {
	mock *MockFrameExporter
}

// NewMockFrameExporter creates a new mock instance.
func NewMockFrameExporter(ctrl *gomock.Controller) *MockFrameExporter {
	mock := &MockFrameExporter{ctrl: ctrl}
	mock.recorder = &MockFrameExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrameExporter) EXPECT() *MockFrameExporterMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockFrameExporter) Export(image domain.FrameImage, mark domain.FrameMark, path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", image, mark, path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockFrameExporterMockRecorder) Export(image, mark, path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockFrameExporter)(nil).Export), image, mark, path, overwrite)
}
