// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: FrameRepository)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/frame_repository.go -package mockdomain . FrameRepository
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFrameRepository is a mock of FrameRepository interface.
type MockFrameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFrameRepositoryMockRecorder
	isgomock struct{}
}

// MockFrameRepositoryMockRecorder is the mock recorder for MockFrameRepository.
type MockFrameRepositoryMockRecorder struct {
	mock *MockFrameRepository
}

// NewMockFrameRepository creates a new mock instance.
func NewMockFrameRepository(ctrl *gomock.Controller) *MockFrameRepository {
	mock := &MockFrameRepository{ctrl: ctrl}
	mock.recorder = &MockFrameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrameRepository) EXPECT() *MockFrameRepositoryMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockFrameRepository) Inspect(dir string, resolution domain.Resolution) (domain.FrameDirectory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", dir, resolution)
	ret0, _ := ret[0].(domain.FrameDirectory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockFrameRepositoryMockRecorder) Inspect(dir, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockFrameRepository)(nil).Inspect), dir, resolution)
}

// Remove mocks base method.
func (m *MockFrameRepository) Remove(dir string, indexes []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", dir, indexes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFrameRepositoryMockRecorder) Remove(dir, indexes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFrameRepository)(nil).Remove), dir, indexes)
}

// Save mocks base method.
func (m *MockFrameRepository) Save(dir string, index int, id domain.FrameSetID, image domain.FrameImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", dir, index, id, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFrameRepositoryMockRecorder) Save(dir, index, id, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFrameRepository)(nil).Save), dir, index, id, image)
}
