// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: GeoDataRepository)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/geo_data_repository.go -package mockdomain . GeoDataRepository
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoDataRepository is a mock of GeoDataRepository interface.
type MockGeoDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGeoDataRepositoryMockRecorder
	isgomock struct{}
}

// MockGeoDataRepositoryMockRecorder is the mock recorder for MockGeoDataRepository.
type MockGeoDataRepositoryMockRecorder struct {
	mock *MockGeoDataRepository
}

// NewMockGeoDataRepository creates a new mock instance.
func NewMockGeoDataRepository(ctrl *gomock.Controller) *MockGeoDataRepository {
	mock := &MockGeoDataRepository{ctrl: ctrl}
	mock.recorder = &MockGeoDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoDataRepository) EXPECT() *MockGeoDataRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockGeoDataRepository) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGeoDataRepositoryMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGeoDataRepository)(nil).Delete), name)
}

// FindByName mocks base method.
func (m *MockGeoDataRepository) FindByName(name string) (domain.GeoDataSource, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(domain.GeoDataSource)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByName indicates an expected call of FindByName.
func (mr *MockGeoDataRepositoryMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockGeoDataRepository)(nil).FindByName), name)
}

// List mocks base method.
func (m *MockGeoDataRepository) List() ([]domain.GeoDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.GeoDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGeoDataRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGeoDataRepository)(nil).List))
}

// Save mocks base method.
func (m *MockGeoDataRepository) Save(source domain.GeoDataSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGeoDataRepositoryMockRecorder) Save(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGeoDataRepository)(nil).Save), source)
}
