// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: GeoSliceExporter)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/geo_slice_exporter.go -package mockdomain . GeoSliceExporter
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoSliceExporter is a mock of GeoSliceExporter interface.
type MockGeoSliceExporter struct {
	ctrl     *gomock.Controller
	recorder *MockGeoSliceExporterMockRecorder
	isgomock struct{}
}

// MockGeoSliceExporterMockRecorder is the mock recorder for MockGeoSliceExporter.
type MockGeoSliceExporterMockRecorder struct {
	mock *MockGeoSliceExporter
}

// NewMockGeoSliceExporter creates a new mock instance.
func NewMockGeoSliceExporter(ctrl *gomock.Controller) *MockGeoSliceExporter {
	mock := &MockGeoSliceExporter{ctrl: ctrl}
	mock.recorder = &MockGeoSliceExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoSliceExporter) EXPECT() *MockGeoSliceExporterMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockGeoSliceExporter) Export(slice domain.GeoSlice, path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", slice, path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockGeoSliceExporterMockRecorder) Export(slice, path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockGeoSliceExporter)(nil).Export), slice, path, overwrite)
}
