// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: GeoSliceReader)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/geo_slice_reader.go -package mockdomain . GeoSliceReader
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoSliceReader is a mock of GeoSliceReader interface.
type MockGeoSliceReader struct {
	ctrl     *gomock.Controller
	recorder *MockGeoSliceReaderMockRecorder
	isgomock struct{}
}

// MockGeoSliceReaderMockRecorder is the mock recorder for MockGeoSliceReader.
type MockGeoSliceReaderMockRecorder struct {
	mock *MockGeoSliceReader
}

// NewMockGeoSliceReader creates a new mock instance.
func NewMockGeoSliceReader(ctrl *gomock.Controller) *MockGeoSliceReader {
	mock := &MockGeoSliceReader{ctrl: ctrl}
	mock.recorder = &MockGeoSliceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoSliceReader) EXPECT() *MockGeoSliceReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockGeoSliceReader) Read(path string) (domain.GeoSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(domain.GeoSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockGeoSliceReaderMockRecorder) Read(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockGeoSliceReader)(nil).Read), path)
}
