// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: Simplifier)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/simplifier.go -package mockdomain . Simplifier
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSimplifier is a mock of Simplifier interface.
type MockSimplifier struct {
	ctrl     *gomock.Controller
	recorder *MockSimplifierMockRecorder
	isgomock struct{}
}

// MockSimplifierMockRecorder is the mock recorder for MockSimplifier.
type MockSimplifierMockRecorder struct {
	mock *MockSimplifier
}

// NewMockSimplifier creates a new mock instance.
func NewMockSimplifier(ctrl *gomock.Controller) *MockSimplifier {
	mock := &MockSimplifier{ctrl: ctrl}
	mock.recorder = &MockSimplifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimplifier) EXPECT() *MockSimplifierMockRecorder {
	return m.recorder
}

// Simplify mocks base method.
func (m *MockSimplifier) Simplify(points []domain.TrackPoint, level domain.Level) []domain.TrackPoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Simplify", points, level)
	ret0, _ := ret[0].([]domain.TrackPoint)
	return ret0
}

// Simplify indicates an expected call of Simplify.
func (mr *MockSimplifierMockRecorder) Simplify(points, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Simplify", reflect.TypeOf((*MockSimplifier)(nil).Simplify), points, level)
}
