// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: Smoother)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/smoother.go -package mockdomain . Smoother
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSmoother is a mock of Smoother interface.
type MockSmoother struct {
	ctrl     *gomock.Controller
	recorder *MockSmootherMockRecorder
	isgomock struct{}
}

// MockSmootherMockRecorder is the mock recorder for MockSmoother.
type MockSmootherMockRecorder struct {
	mock *MockSmoother
}

// NewMockSmoother creates a new mock instance.
func NewMockSmoother(ctrl *gomock.Controller) *MockSmoother {
	mock := &MockSmoother{ctrl: ctrl}
	mock.recorder = &MockSmootherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmoother) EXPECT() *MockSmootherMockRecorder {
	return m.recorder
}

// Smooth mocks base method.
func (m *MockSmoother) Smooth(points []domain.TrackPoint, level domain.Level) []domain.TrackPoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Smooth", points, level)
	ret0, _ := ret[0].([]domain.TrackPoint)
	return ret0
}

// Smooth indicates an expected call of Smooth.
func (mr *MockSmootherMockRecorder) Smooth(points, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Smooth", reflect.TypeOf((*MockSmoother)(nil).Smooth), points, level)
}
