// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: TileDecoder)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/tile_decoder.go -package mockdomain . TileDecoder
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTileDecoder is a mock of TileDecoder interface.
type MockTileDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockTileDecoderMockRecorder
	isgomock struct{}
}

// MockTileDecoderMockRecorder is the mock recorder for MockTileDecoder.
type MockTileDecoderMockRecorder struct {
	mock *MockTileDecoder
}

// NewMockTileDecoder creates a new mock instance.
func NewMockTileDecoder(ctrl *gomock.Controller) *MockTileDecoder {
	mock := &MockTileDecoder{ctrl: ctrl}
	mock.recorder = &MockTileDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTileDecoder) EXPECT() *MockTileDecoderMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockTileDecoder) Decode(format string, data []byte) (domain.TileImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", format, data)
	ret0, _ := ret[0].(domain.TileImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockTileDecoderMockRecorder) Decode(format, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockTileDecoder)(nil).Decode), format, data)
}
