// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: TrackParser)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/track_parser.go -package mockdomain . TrackParser
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	io "io"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTrackParser is a mock of TrackParser interface.
type MockTrackParser struct {
	ctrl     *gomock.Controller
	recorder *MockTrackParserMockRecorder
	isgomock struct{}
}

// MockTrackParserMockRecorder is the mock recorder for MockTrackParser.
type MockTrackParserMockRecorder struct {
	mock *MockTrackParser
}

// NewMockTrackParser creates a new mock instance.
func NewMockTrackParser(ctrl *gomock.Controller) *MockTrackParser {
	mock := &MockTrackParser{ctrl: ctrl}
	mock.recorder = &MockTrackParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackParser) EXPECT() *MockTrackParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockTrackParser) Parse(r io.Reader) (domain.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", r)
	ret0, _ := ret[0].(domain.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockTrackParserMockRecorder) Parse(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockTrackParser)(nil).Parse), r)
}
