// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: VideoEncoder)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/video_encoder.go -package mockdomain . VideoEncoder
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	context "context"
	reflect "reflect"

	domain "github.com/waliqueiroz/sobrevoo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoEncoder is a mock of VideoEncoder interface.
type MockVideoEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockVideoEncoderMockRecorder
	isgomock struct{}
}

// MockVideoEncoderMockRecorder is the mock recorder for MockVideoEncoder.
type MockVideoEncoderMockRecorder struct {
	mock *MockVideoEncoder
}

// NewMockVideoEncoder creates a new mock instance.
func NewMockVideoEncoder(ctrl *gomock.Controller) *MockVideoEncoder {
	mock := &MockVideoEncoder{ctrl: ctrl}
	mock.recorder = &MockVideoEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoEncoder) EXPECT() *MockVideoEncoderMockRecorder {
	return m.recorder
}

// Encode mocks base method.
func (m *MockVideoEncoder) Encode(ctx context.Context, job domain.EncodeJob, progress func(int)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", ctx, job, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockVideoEncoderMockRecorder) Encode(ctx, job, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockVideoEncoder)(nil).Encode), ctx, job, progress)
}

// Probe mocks base method.
func (m *MockVideoEncoder) Probe(ctx context.Context) (domain.EncoderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx)
	ret0, _ := ret[0].(domain.EncoderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockVideoEncoderMockRecorder) Probe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockVideoEncoder)(nil).Probe), ctx)
}
