// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: VideoExporter)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/video_exporter.go -package mockdomain . VideoExporter
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVideoExporter is a mock of VideoExporter interface.
type MockVideoExporter struct {
	ctrl     *gomock.Controller
	recorder *MockVideoExporterMockRecorder
	isgomock struct{}
}

// MockVideoExporterMockRecorder is the mock recorder for MockVideoExporter.
type MockVideoExporterMockRecorder struct {
	mock *MockVideoExporter
}

// NewMockVideoExporter creates a new mock instance.
func NewMockVideoExporter(ctrl *gomock.Controller) *MockVideoExporter {
	mock := &MockVideoExporter{ctrl: ctrl}
	mock.recorder = &MockVideoExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoExporter) EXPECT() *MockVideoExporterMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockVideoExporter) Check(path string, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", path, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockVideoExporterMockRecorder) Check(path, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockVideoExporter)(nil).Check), path, overwrite)
}

// Export mocks base method.
func (m *MockVideoExporter) Export(path string, overwrite bool, produce func(string) error) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", path, overwrite, produce)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockVideoExporterMockRecorder) Export(path, overwrite, produce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockVideoExporter)(nil).Export), path, overwrite, produce)
}
