// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/waliqueiroz/sobrevoo/internal/domain (interfaces: Workspace)
//
// Generated by this command:
//
//	mockgen -destination mockdomain/workspace.go -package mockdomain . Workspace
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// EnsureDirectory mocks base method.
func (m *MockWorkspace) EnsureDirectory(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDirectory", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDirectory indicates an expected call of EnsureDirectory.
func (mr *MockWorkspaceMockRecorder) EnsureDirectory(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDirectory", reflect.TypeOf((*MockWorkspace)(nil).EnsureDirectory), path)
}

// NewTemporary mocks base method.
func (m *MockWorkspace) NewTemporary() (string, func() error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTemporary")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func() error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewTemporary indicates an expected call of NewTemporary.
func (mr *MockWorkspaceMockRecorder) NewTemporary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTemporary", reflect.TypeOf((*MockWorkspace)(nil).NewTemporary))
}
